### ISSUE TITLE
Hide "Still Awake" Menu Item After 2 Hours Asleep

### ISSUE THREAD

**Issue by petykowski** [spetykowski/sleepy#11]
It is unlikely that a user will start sleep session and not be asleep after 2 hours. Menu item should no longer be visible to user.

**Comment by nsseverson** [comment]
## To Do
- [x] Inside of the Menu Action Method sleepDidStart, create an NS Timer.
- [x] The NS Timer should be set to 15 seconds for testing
- [x] After 15 Seconds the tiemr should call the selector (prepareMenuIconsForTwoHoursAfterSleep), the one we made yesterday.
- [x] Test

**Comment by nsseverson** [comment]
## Update

Successfully tested 15s NSTimer calling selector

## To Do
- Figure out how to stop timer for other selections by user
- Figure out how this method impacts other workflows (wake, cancel, etc.)

**Comment by petykowski** [comment]
### Failed Testing
* While testing this ticket, it was observed that after 2 hours the menu icons were still presented to the user.
